# Generated by Django 6.0.5 on 2026-07-11 18:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papervoult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
