# Generated by Django 6.0.5 on 2026-07-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papervoult', '0002_alter_paper_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(upload_to='papers/'),
        ),
    ]
