# Generated by Django 6.0.5 on 2026-07-12 08:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papervoult', '0003_alter_paper_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
